---
- hosts: mywebservers
  become: yes
  tasks:
   - name: Install java on Ubuntu
     apt:
      name: openjdk-11-jdk
      state: present
     when: ansible_os_family == "Debian"
   - name: Install java on Ubuntu
     apt:
      name: java-11-openjdk
      state: present
     when: ansible_os_family == "RedHat"