---
- hosts: mywebservers
  become: yes
  tasks:
   - name: Install java on Ubuntu
     apt:
      name: "{{myjavapackonubuntu}}"
      state: present
     when: ansible_os_family == "Debian"
   - name: Install java on RedHat
     yum:
      name: "{{myjavapackonredhat}}"
      state: present
     when: ansible_os_family == "RedHat"