---
- hosts: 172.31.18.148
  become: yes
  tasks:
  - include_tasks: myfilehandeling.yml
  - name: create a directory
    file:
      path: /home/pinku/myfolder
      state: directory
  - name: copy a file
    copy:
      src: my2ndfile.txt
      dest: /home/pinku/myfolder