---
- hosts: mywebservers
  become: yes
  tasks: 
  - name: i want to install webserver on Debian Server
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
  - name: i want to start webserver
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
  - name: i want to install webserver on RedHat Server
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
  - name: i want to start webserver
    service: 
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
