---
# tasks file for mytomcatrole
- include_tasks: addtomcatuser.yml
- include_tasks: installjava.yml
- include_tasks: downloadtomcat.yml
- include_tasks: permission.yml
- include_tasks: tomcatdashboard.yml
- include_tasks: systemctl.yml
- include_tasks: ufwallow.yml
- include_tasks: deployjavaprogram.yml