---
- hosts: localhost
  become: yes
  tasks:
  - name: create ansible node
    ec2:
     key_name: mykey
     instance_type: t2.micro
     image: ami-123456
     wait: yes
     region: us-east-1
     group: webserver
     count: 1
     vpc_subnet_id: subnet-29e63245
     assign_public_ip: yes
     instance_tags:
        Name: ansiblenodes