---
- name: Install "mariadb-server" package
  apt:
    name: mariadb-server
    state: present

- name: Install "mariadb-client" package
  apt:
    name: mariadb-client
    state: present

- name: start mariadb.service
  systemd:
    name: mariadb.service
    state: started